# Generated by Django 3.2 on 2023-09-22 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('trip', '0002_auto_20230921_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attraction_banner', to='user.media'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_banner', to='user.media'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_image', to='user.media'),
        ),
        migrations.AlterField(
            model_name='familyfun',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fun_banner', to='user.media'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_banner', to='user.media'),
        ),
        migrations.AlterField(
            model_name='park',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='park_banner', to='user.media'),
        ),
        migrations.AlterField(
            model_name='weirdandwacky',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weirdandwacky_banner', to='user.media'),
        ),
    ]
