# Generated by Django 4.1.7 on 2024-07-02 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='trip_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.city'),
        ),
        migrations.AddField(
            model_name='plan',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
