# Generated by Django 3.2 on 2023-09-29 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230925_0827'),
        ('trip', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtremeSport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(null=True)),
                ('meta_data', models.JSONField(default=dict)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extremesport_city', to='trip.city')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_banner', to='user.media')),
            ],
            options={
                'verbose_name': 'Extreme Sport',
                'verbose_name_plural': 'Extreme Sports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(null=True)),
                ('meta_data', models.JSONField(default=dict)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicalsite_city', to='trip.city')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_banner', to='user.media')),
            ],
            options={
                'verbose_name': 'Historical Site',
                'verbose_name_plural': 'Historical Sites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='camp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Camp', 'verbose_name_plural': 'Camps'},
        ),
        migrations.AlterModelOptions(
            name='familyfun',
            options={'ordering': ['-created_at'], 'verbose_name': 'Family Fun', 'verbose_name_plural': 'Family Fun'},
        ),
        migrations.AlterModelOptions(
            name='weirdandwacky',
            options={'ordering': ['-created_at'], 'verbose_name': 'Weird And Wacky', 'verbose_name_plural': 'Weird And Wacky'},
        ),
        migrations.AlterField(
            model_name='attraction',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='camp',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='drivewebsite',
            name='url_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='familyfun',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='familyfun',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weirdandwacky',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='weirdandwacky',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
