# Generated by Django 4.1.7 on 2024-07-17 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_remove_plan_user_planuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_attractions',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_events',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_extremesports',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_historicalsites',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_hotels',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_parks',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_wierdandwacky',
        ),
        migrations.CreateModel(
            name='UserLikesWeirdAndWacky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.plan')),
                ('userlikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.userlikes')),
                ('weirdandwacky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.weirdandwacky')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikesPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.park')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.plan')),
                ('userlikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.userlikes')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikesHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.hotel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.plan')),
                ('userlikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.userlikes')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikesHistoricalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historicalsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.historicalsite')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.plan')),
                ('userlikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.userlikes')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikesExtremeSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extremesport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.extremesport')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.plan')),
                ('userlikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.userlikes')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.event')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.plan')),
                ('userlikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.userlikes')),
            ],
        ),
        migrations.CreateModel(
            name='UserLikesAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.attraction')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.plan')),
                ('userlikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.userlikes')),
            ],
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liked_attractions_new',
            field=models.ManyToManyField(through='trip.UserLikesAttraction', to='trip.attraction'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liked_events_new',
            field=models.ManyToManyField(through='trip.UserLikesEvent', to='trip.event'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liked_extremesports_new',
            field=models.ManyToManyField(through='trip.UserLikesExtremeSport', to='trip.extremesport'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liked_historicalsites_new',
            field=models.ManyToManyField(through='trip.UserLikesHistoricalSite', to='trip.historicalsite'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liked_hotels_new',
            field=models.ManyToManyField(through='trip.UserLikesHotel', to='trip.hotel'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liked_parks_new',
            field=models.ManyToManyField(through='trip.UserLikesPark', to='trip.park'),
        ),
        migrations.AddField(
            model_name='userlikes',
            name='liked_wierdandwacky_new',
            field=models.ManyToManyField(through='trip.UserLikesWeirdAndWacky', to='trip.weirdandwacky'),
        ),
    ]
