# Generated by Django 4.1.7 on 2024-07-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_remove_userlikes_liked_attractions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=80)),
                ('nicename', models.CharField(max_length=80)),
                ('iso3', models.CharField(max_length=3)),
                ('numeric_code', models.IntegerField(null=True)),
                ('phone_code', models.IntegerField(null=True)),
            ],
            options={
                'db_table': '"country"',
            },
        ),
    ]
