# Generated by Django 3.2 on 2023-10-05 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='image',
        ),
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='extremesport',
            name='image',
        ),
        migrations.RemoveField(
            model_name='familyfun',
            name='image',
        ),
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='park',
            name='image',
        ),
        migrations.RemoveField(
            model_name='weirdandwacky',
            name='image',
        ),
        migrations.AddField(
            model_name='attraction',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='camp',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='city',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='extremesport',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='familyfun',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='food',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='park',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='weirdandwacky',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
    ]
