# Generated by Django 4.1.7 on 2024-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_motivation_priority_travelgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': '"airline_brand"',
            },
        ),
        migrations.CreateModel(
            name='HotelBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': '"hotel_brand"',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': '"restaurant_brand"',
            },
        ),
    ]
