# Generated by Django 3.2 on 2023-10-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_auto_20231005_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
