# Generated by Django 3.2 on 2023-10-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_city_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
