# Generated by Django 4.1.7 on 2024-07-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_airlinebrand_hotelbrand_restaurantbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
