# Generated by Django 4.1.7 on 2024-08-02 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_alter_country_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikesattraction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='userlikesevent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='userlikesextremesport',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='userlikeshistoricalsite',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='userlikeshotel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='userlikespark',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='userlikesweirdandwacky',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
    ]
