# Generated by Django 3.2 on 2024-01-24 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0011_auto_20240108_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_attractions', models.ManyToManyField(to='trip.Attraction')),
                ('liked_events', models.ManyToManyField(to='trip.Event')),
                ('liked_extremesports', models.ManyToManyField(to='trip.ExtremeSport')),
                ('liked_historicalsites', models.ManyToManyField(to='trip.HistoricalSite')),
                ('liked_hotels', models.ManyToManyField(to='trip.Hotel')),
                ('liked_parks', models.ManyToManyField(to='trip.Park')),
                ('liked_wierdandwacky', models.ManyToManyField(to='trip.WeirdAndWacky')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
