# Generated by Django 4.1.7 on 2024-08-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_userlikesattraction_category_userlikesevent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikesattraction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userlikesevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userlikesextremesport',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userlikeshistoricalsite',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userlikeshotel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userlikespark',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userlikesweirdandwacky',
            name='category',
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='extremesport',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='park',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
        migrations.AddField(
            model_name='weirdandwacky',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category'),
        ),
    ]
