# Generated by Django 3.2 on 2024-01-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_userlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='camp',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='extremesport',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='familyfun',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='park',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='weirdandwacky',
            name='is_favorite',
        ),
    ]
