# Generated by Django 4.1.7 on 2024-08-13 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_plancategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.category')),
            ],
            options={
                'verbose_name': 'Plan Category',
                'verbose_name_plural': 'Plan Categories',
                'ordering': ['-created_at'],
            },
        ),
    ]
