# Generated by Django 4.1.7 on 2024-06-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_auto_20240205_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=200)),
            ],
            options={
                'db_table': '"media"',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '"status"',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='end_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='place_id',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='start_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='user_ratings_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.media'),
        ),
    ]
