# Generated by Django 4.1.7 on 2024-08-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_tripcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': '"rental_cars"',
            },
        ),
    ]
