# Generated by Django 4.1.7 on 2024-06-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_media_status_hotel_end_price_hotel_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('html_attributions', models.TextField()),
                ('photo_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_code', models.CharField(max_length=50)),
                ('global_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viewport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('northeast_lat', models.FloatField(null=True)),
                ('northeast_lng', models.FloatField(null=True)),
                ('southwest_lat', models.FloatField(null=True)),
                ('southwest_lng', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trip.location')),
                ('viewport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trip.viewport')),
            ],
        ),
    ]
