# Generated by Django 4.1.7 on 2024-06-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0016_location_photo_pluscode_viewport_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='business_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='discount_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='geometry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.geometry'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='icon_background_color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='icon_mask_base_uri',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='open_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photos',
            field=models.ManyToManyField(to='trip.photo'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='plus_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.pluscode'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='scope',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='types',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='vicinity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
