# Generated by Django 4.1.7 on 2024-09-02 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0016_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryWeirdAndWacky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.itinerary')),
                ('weirdandwacky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.weirdandwacky')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.itinerary')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.park')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.hotel')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryHistoricalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historicalsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.historicalsite')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryExtremeSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extremesport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.extremesport')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.event')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.itinerary')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.attraction')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.itinerary')),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='attractions_itinerary',
            field=models.ManyToManyField(through='trip.ItineraryAttraction', to='trip.attraction'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='events_itinerary',
            field=models.ManyToManyField(through='trip.ItineraryEvent', to='trip.event'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='extremesports_itinerary',
            field=models.ManyToManyField(through='trip.ItineraryExtremeSport', to='trip.extremesport'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='historicalsites_itinerary',
            field=models.ManyToManyField(through='trip.ItineraryHistoricalSite', to='trip.historicalsite'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='hotel_itinerary',
            field=models.ManyToManyField(through='trip.ItineraryHotel', to='trip.hotel'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='parks_itinerary',
            field=models.ManyToManyField(through='trip.ItineraryPark', to='trip.park'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='wierdandwacky_itinerary',
            field=models.ManyToManyField(through='trip.ItineraryWeirdAndWacky', to='trip.weirdandwacky'),
        ),
    ]
