# Generated by Django 4.1.7 on 2024-06-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_hotel_business_status_hotel_discount_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='user_ratings_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
