# Generated by Django 4.1.7 on 2024-09-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_itineraryweirdandwacky_itinerarypark_itineraryhotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='plan',
        ),
        migrations.AddField(
            model_name='itineraryattraction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.plan'),
        ),
        migrations.AddField(
            model_name='itineraryevent',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.plan'),
        ),
        migrations.AddField(
            model_name='itineraryextremesport',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.plan'),
        ),
        migrations.AddField(
            model_name='itineraryhistoricalsite',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.plan'),
        ),
        migrations.AddField(
            model_name='itineraryhotel',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.plan'),
        ),
        migrations.AddField(
            model_name='itinerarypark',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.plan'),
        ),
        migrations.AddField(
            model_name='itineraryweirdandwacky',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.plan'),
        ),
    ]
