# Generated by Django 4.1.7 on 2024-09-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_remove_itinerary_plan_itineraryattraction_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='date',
        ),
        migrations.AddField(
            model_name='itineraryattraction',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryevent',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryextremesport',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryhistoricalsite',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryhotel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itinerarypark',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itineraryweirdandwacky',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
