# Generated by Django 4.1.7 on 2024-11-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_itinerarysite_userlikessite_remove_camp_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryhotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='itineraryhotel',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='itineraryhotel',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userlikeshotel',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='userlikeshotel',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userlikeshotel',
            name='userlikes',
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-created_at'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='hotel_itinerary',
        ),
        migrations.RemoveField(
            model_name='userlikes',
            name='liked_hotels_new',
        ),
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='amenities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='business_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='check_in_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='cover_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='discount_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='end_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='facility_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='geometry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.geometry'),
        ),
        migrations.AddField(
            model_name='site',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='icon_background_color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='icon_mask_base_uri',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.media'),
        ),
        migrations.AddField(
            model_name='site',
            name='open_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='photos',
            field=models.ManyToManyField(to='trip.photo'),
        ),
        migrations.AddField(
            model_name='site',
            name='place_id',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='site',
            name='plus_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.pluscode'),
        ),
        migrations.AddField(
            model_name='site',
            name='policy',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='reviews',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='scope',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='service_amenities',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='start_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='types',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='user_ratings_total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='vicinity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pluscode',
            name='compound_code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pluscode',
            name='global_code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='ItineraryHotel',
        ),
        migrations.DeleteModel(
            name='UserLikesHotel',
        ),
    ]
