# Generated by Django 4.1.7 on 2024-11-13 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0021_remove_itineraryhotel_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometry',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.location'),
        ),
        migrations.AlterField(
            model_name='geometry',
            name='viewport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.viewport'),
        ),
    ]
