# Generated by Django 4.1.7 on 2024-11-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0022_alter_geometry_location_alter_geometry_viewport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='place_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
