# Generated by Django 4.1.7 on 2024-11-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0023_alter_site_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='place_id',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
