# Generated by Django 4.1.7 on 2024-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0024_alter_site_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluscode',
            name='compound_code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pluscode',
            name='global_code',
            field=models.CharField(max_length=250),
        ),
    ]
