# Generated by Django 4.1.7 on 2024-11-13 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0025_alter_pluscode_compound_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
    ]
