# Generated by Django 4.1.7 on 2024-11-13 13:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat_long',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None),
        ),
    ]
