# Generated by Django 4.1.7 on 2024-11-18 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0028_alter_site_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='lat_long',
        ),
    ]
