# Generated by Django 4.1.7 on 2024-11-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0029_remove_city_lat_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat_long',
            field=models.JSONField(default=list),
        ),
    ]
