# Generated by Django 4.1.7 on 2024-11-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0030_city_lat_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scrape',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='scrape',
            field=models.BooleanField(default=False),
        ),
    ]
