# Generated by Django 4.1.7 on 2024-11-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0032_alter_site_latitude_alter_site_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='site',
            name='plus_code',
        ),
        migrations.DeleteModel(
            name='Geometry',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PlusCode',
        ),
        migrations.DeleteModel(
            name='Viewport',
        ),
    ]
