# Generated by Django 4.1.7 on 2024-11-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0033_remove_site_geometry_remove_site_plus_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='place_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
