# Generated by Django 4.1.7 on 2024-12-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0035_site_ad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='keyword',
            field=models.TextField(null=True),
        ),
    ]
