# Generated by Django 4.1.7 on 2024-12-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0036_site_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='keyword',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
