# Generated by Django 4.1.7 on 2024-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0037_alter_site_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
