# Generated by Django 4.1.7 on 2024-12-20 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0039_site_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField(null=True)),
                ('original_text', models.TextField(null=True)),
                ('author_name', models.CharField(max_length=500, null=True)),
                ('author_photo_uri', models.TextField(null=True)),
                ('publish_time', models.DateTimeField()),
                ('flag_content_uri', models.URLField()),
                ('google_maps_uri', models.URLField()),
            ],
            options={
                'verbose_name': 'Place Review',
                'verbose_name_plural': 'Place Reviews',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='APICalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('result_count', models.IntegerField(null=True)),
                ('request_body', models.JSONField(default=dict)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trip.category')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.city')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='place_review',
            field=models.ManyToManyField(to='trip.placereview'),
        ),
    ]
