# Generated by Django 4.1.7 on 2024-12-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0040_placereview_photo_photo_name_apicalls_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='author_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='author_photo_uri',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='author_uri',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='placereview',
            name='author_uri',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
