# Generated by Django 4.1.7 on 2024-12-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0042_alter_apicalls_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicalls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apicalls',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
