# Generated by Django 4.1.7 on 2024-12-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0043_apicalls_created_at_apicalls_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='property_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='rate_pretty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='rate_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
