# Generated by Django 4.1.7 on 2024-12-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0044_site_property_id_site_rate_pretty_site_rate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='city_anchor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
