# Generated by Django 4.1.7 on 2024-12-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0046_alter_itinerarysite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarysite',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
