# Generated by Django 4.1.7 on 2024-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0048_alter_itinerarysite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
