# Generated by Django 4.1.7 on 2025-01-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0049_alter_plan_end_date_alter_plan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='route',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
