# Generated by Django 4.1.7 on 2025-01-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0051_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='event_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
