# Generated by Django 4.1.7 on 2025-01-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0052_photo_url_site_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='regular_opening_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='regular_secondary_opening_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
