# Generated by Django 4.1.7 on 2025-01-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0053_site_regular_opening_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='event_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
