# Generated by Django 4.1.7 on 2025-01-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0054_site_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author_photo_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
