# Generated by Django 4.1.7 on 2025-01-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0055_alter_photo_author_photo_uri_alter_photo_author_uri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author_photo_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='author_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
