# Generated by Django 3.2 on 2025-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0057_keyword_category_keywords_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_reference',
            field=models.TextField(null=True),
        ),
    ]
