# Generated by Django 4.2.21 on 2025-06-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0058_auto_20250522_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='static',
            field=models.URLField(blank=True, null=True),
        ),
    ]
