# Generated by Django 4.1.7 on 2024-06-24 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('query', models.TextField(db_index=True, verbose_name='Search Query')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('chat_gpt_response', models.JSONField(default=dict, verbose_name='ChatGPT Response')),
                ('api_response', models.JSONField(default=dict, verbose_name='API Response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search Log',
                'verbose_name_plural': 'Search Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
