# Generated by Django 3.2 on 2024-02-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
