# Generated by Django 3.2 on 2023-11-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230925_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialloginmodel',
            name='provider',
            field=models.CharField(blank=True, choices=[('Google', 'google'), ('Facebook', 'facebook'), ('Apple', 'apple')], max_length=16, null=True),
        ),
    ]
