# Generated by Django 4.1.7 on 2024-07-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_loyaltyprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='user',
        ),
    ]
