# Generated by Django 4.1.7 on 2024-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_loyaltyprogram_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
