# Generated by Django 3.2 on 2023-11-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userplantriplogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplantriplogs',
            name='route_request_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
