# Generated by Django 3.2 on 2023-11-06 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userplantriplogs_route_request_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplantriplogs',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Trip Log', 'verbose_name_plural': 'User Trip Log'},
        ),
        migrations.AddField(
            model_name='userplantriplogs',
            name='response_time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
