# Generated by Django 3.2 on 2024-01-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_socialloginmodel_provider'),
        ('user', '0005_auto_20231106_0544'),
    ]

    operations = [
    ]
