# Generated by Django 3.2 on 2024-01-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20240108_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
