# Generated by Django 3.2 on 2024-01-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_user_meta_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userplantriplogs",
            name="travel_time",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
