# Generated by Django 4.1.7 on 2024-06-15 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20240205_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignupVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=225, null=True)),
                ('verification_code', models.CharField(max_length=255)),
                ('expiry_time', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
