# Generated by Django 4.1.7 on 2024-07-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
