# Generated by Django 4.1.7 on 2024-05-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='icon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
