# Generated by Django 4.1.7 on 2024-11-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_delete_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='category',
            name='media',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='geometry',
            name='location',
        ),
        migrations.RemoveField(
            model_name='geometry',
            name='viewport',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='geometry',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='plus_code',
        ),
        migrations.RemoveField(
            model_name='hotelmedia',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelmedia',
            name='media',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Geometry',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='HotelMedia',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='PlusCode',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Viewport',
        ),
    ]
