# Generated by Django 4.1.7 on 2024-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='icon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
