# Generated by Django 4.1.7 on 2024-05-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_media_hotel_rating_hotel_user_ratings_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='end_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='start_price',
            field=models.FloatField(null=True),
        ),
    ]
