# Generated by Django 4.1.7 on 2024-06-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_banner_plan_status_tax_customer_category_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('html_attributions', models.TextField()),
                ('photo_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlusCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_code', models.CharField(max_length=50)),
                ('global_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viewport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('northeast_lat', models.FloatField(null=True)),
                ('northeast_lng', models.FloatField(null=True)),
                ('southwest_lat', models.FloatField(null=True)),
                ('southwest_lng', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='end_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='media',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='start_price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='business_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='icon_background_color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='icon_mask_base_uri',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='open_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='scope',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='types',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='vicinity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='icon',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='place_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='user_ratings_total',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.location')),
                ('viewport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotels.viewport')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='geometry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.geometry'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photos',
            field=models.ManyToManyField(to='hotels.photo'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='plus_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.pluscode'),
        ),
    ]
