# Generated by Django 4.1.7 on 2024-06-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_location_photo_pluscode_viewport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='discount_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
