ONE_HOUR = 3600
HALF_HOUR = ONE_HOUR / 2
SIX_HOURS = ONE_HOUR * 6
HALF_DAY = ONE_HOUR * 12
ONE_DAY = ONE_HOUR * 24
FIVE_DAY = ONE_DAY * 5
ONE_WEEK = ONE_DAY * 7
ONE_MONTH = ONE_DAY * 30
ONE_YEAR = ONE_MONTH * 12


USER_TOKEN = "user_token_{user_id}_{token}"

